### ISSUE TITLE
How hard is it?

### ISSUE THREAD

**Issue by karl-police** [Pseudoreality/Roblox-Identities#1]
If I wanted that little window next to the command bar. And I do know some other things exist, like a Fast Flag Editor.

How hard is it gonna be to enable it? I failed enabling the Fast Flag Editor, but I also was probably using IDA like an idiot.

&nbsp;

I won't ever seek stopping trying to figure out... but maybe I am looking at the wrong place.

**Comment by karl-police** [comment]
Unless you have discovered this and then discovered further https://github.com/search?q=repo%3AMaximumADHD%2FRoblox-Studio-Mod-Manager%20RobloxInternal&type=code

**Comment by karl-police** [comment]
ok.. I've enabled it, though can't do all security levels and also roblox crashes a lot so idk

**Comment by Pseudoreality** [comment]
Oh I'm pretty late to this 😅
The command bar is a feature of Roblox Internal. I wouldn't say it's too hard if you know how to open the program in a debugger and switch some bytes around. Max's patcher most likely just switches the bytes around.

For me, it was more difficult to use the debugger for the first time.

All security levels is my own thing I put into it though. By default it should only have GameScript, CommandBar, and ElevatedStudioPlugin.

**Comment by karl-police** [comment]
> Oh I'm pretty late to this 😅 The command bar is a feature of Roblox Internal. I wouldn't say it's too hard if you know how to open the program in a debugger and switch some bytes around. Max's patcher most likely just switches the bytes around.
> 
> For me, it was more difficult to use the debugger for the first time.
> 
> All security levels is my own thing I put into it though. By default it should only have GameScript, CommandBar, and ElevatedStudioPlugin.

I wanted to know how you put the levels in on your own. I figured out how to enable Internal, it's just one byte that you change.

**Comment by Pseudoreality** [comment]
Well, that's a bit more editing and a lot more difficult than just enabling Internal if you're planning on making it look nice.

You'd have to change out the three identities with a different number, which is assigned where the dropdown menu options are created. If you know the identity numbers, it's fairly easy to figure out which is which.

**That's good enough for getting the different levels**, but the names aren't going to change on the dropdown, which is a lot more complicated to achieve across all versions of Studio (if something is slightly wrong, an update can break it completely) and I would look somewhere else for something similar to that to get some ideas. If you don't want the text, that's okay because all it does it make it look nice anyway.

**Comment by karl-police** [comment]
> Well, that's a bit more editing and a lot more difficult than just enabling Internal if you're planning on making it look nice.
> 
> You'd have to change out the three identities with a different number, which is assigned where the dropdown menu options are created. If you know the identity numbers, it's fairly easy to figure out which is which.
> 
> **That's good enough for getting the different levels**, but the names aren't going to change on the dropdown, which is a lot more complicated to achieve across all versions of Studio (if something is slightly wrong, an update can break it completely) and I would look somewhere else for something similar to that to get some ideas. If you don't want the text, that's okay because all it does it make it look nice anyway.

I know the indentity numbers. I was able to change them in Cheat Engine. But I wasn't able to change the text or add them to the actual dropdown. I am not sure how you idenitified where the ADDRESS location and etc. for that is.

I used IDA, but I am not sure how I can identify where what is. Breakpoints on IDA is very laggy. How did you do it?


Also do you know how to remove the Signatures from the Built-In Plugins?

**Comment by Pseudoreality** [comment]
Adding them isn't possible (would involve adding bytes to the exe, which is a no-no from my understanding). Changing the text is sorta easy, if you're able to change the offset of the string to the identity names (they have all of the identities listed in one straight line in the bin.)
I would do your own research in this topic though, since I'm not too sure how to explain how that works.

I use x64dbg since IDA was a bit harder for me to work with since I was a beginner with that sort of thing.

I don't. I tried to find a way but dropped it because Roblox Internal always skips the signature check for Built-In Plugins anyway.

**Comment by karl-police** [comment]
> Adding them isn't possible (would involve adding bytes to the exe, which is a no-no from my understanding). Changing the text is sorta easy, if you're able to change the offset of the string to the identity names (they have all of the identities listed in one straight line in the bin.) I would do your own research in this topic though, since I'm not too sure how to explain how that works.
> 
> I use x64dbg since IDA was a bit harder for me to work with since I was a beginner with that sort of thing.
> 
> I don't. I tried to find a way but dropped it because Roblox Internal always skips the signature check for Built-In Plugins anyway.

hmm when I drag in a .rbxm with a Signature it doesn't work, it says the file would be corrupted.

**Comment by Pseudoreality** [comment]
Ahhh, you're talking about doing that.

I haven't been able to do anything, but I haven't looked into it since anything I would be able to get from a signed models would be useless to me, since the scripts just have bytecode in them, no source code. This is especially the case on Built-In Plugins.

I know you *used* to be able to drag the DataModelPatch (signed model with all of the CoreScripts) in just fine, but they made some update that broke that on purpose.

Not sure how to help you out there, sorry.

**Comment by karl-police** [comment]
> Ahhh, you're talking about doing that.
> 
> I haven't been able to do anything, but I haven't looked into it since anything I would be able to get from a signed models would be useless to me, since the scripts just have bytecode in them, no source code. This is especially the case on Built-In Plugins.
> 
> I know you _used_ to be able to drag the DataModelPatch (signed model with all of the CoreScripts) in just fine, but they made some update that broke that on purpose.
> 
> Not sure how to help you out there, sorry.

How did you manage to find the addresses for the strings for the Command Bar stuff... well I guess Cheat Engine would expose those too. But did you manually write in the strings or just changed a value, similar to Enums?

**Comment by Pseudoreality** [comment]
I would look into [x64dbg](https://x64dbg.com/), it helped me a lot with all of that stuff, and I won't be able to explain it too well in a legible way.

The most I'll be able to say is that you can search for the strings themselves, I had to edit the source strings since they were in camelCase, then change the dropdown options to display those strings instead. You may have to make your own program to handle changing the identities.

 I wish you good luck. :)

**Comment by 5h1b** [comment]
> You'd have to change out the three identities with a different number, which is assigned where the dropdown menu options are created. If you know the identity numbers, it's fairly easy to figure out which is which.
>
sorry for me replying to a old message, but i was wondering where is this located at? i want to change the identity level of ElevatedStudioPlugin from 6 to 7 (if i can do that without downloading something like [x64dbg](https://x64dbg.com/))
(I have [HxD](http://mh-nexus.de/hxd) if i need to edit any Hex.)
